application: vnitstudentnotifications
version: 6
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin
- url: /_ah/stats/.*
  script: djangoappengine.appstats.application
- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /static
  static_dir: static
- url: /.*
  script: djangoappengine.main.application

libraries:
- name: webapp2
  version: "2.5.1"
- name: lxml
  version: "latest"
