application: vnitsiteupdates
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /style\.css
  static_files: static/style.css
  upload: static/style\.css
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
